# Refactored strategy with clean config structure
name: "anchors-transitions-and-htf-bias"
meta:
  version: "1.4.0"
  author: "you"
  description: "Demonstrates YAML anchors, state transitions, and daily bias gating."
  created_at: "2025-08-10T09:25:00Z"

# Reusable configuration section
config:
  # Bias conditions for directional filtering
  bias:
    long: &bias_long
      signal: bias.daily
      operator: "=="
      value: "bull"
      timeframe: "1d"
    short: &bias_short
      signal: bias.daily
      operator: "=="
      value: "bear"
      timeframe: "1d"
  
  # Breakout signals for entry timing
  breakout:
    up: &breakout_up
      signal: breakout.state
      operator: changes_to
      value: "up"
      timeframe: "15"
    down: &breakout_down
      signal: breakout.state
      operator: changes_to
      value: "down"
      timeframe: "15"
    fail_up: &breakout_fail_up
      signal: breakout.state
      operator: changes_to
      value: "fail_up"
      timeframe: "15"
    fail_down: &breakout_fail_down
      signal: breakout.state
      operator: changes_to
      value: "fail_down"
      timeframe: "15"
  
  # Trend persistence conditions
  persistence:
    uptrend: &persist_up
      signal: regime.state
      operator: remains
      value: "bull_trend"
      timeframe: "60"
      lookback: 2
    downtrend: &persist_down
      signal: regime.state
      operator: remains
      value: "bear_trend"
      timeframe: "60"
      lookback: 2
  
  # RSI extremes for exits
  rsi:
    overbought: &rsi_overbought
      signal: rsi.value
      operator: ">"
      value: 70
      timeframe: "15"
    oversold: &rsi_oversold
      signal: rsi.value
      operator: "<"
      value: 30
      timeframe: "15"

timeframes: ["15","60","1d"]

entry:
  long:
    mode: all
    conditions:
      - *bias_long
      - *persist_up
      - *breakout_up
  short:
    mode: all
    conditions:
      - *bias_short
      - *persist_down
      - *breakout_down

exit:
  long:
    mode: any
    conditions:
      - *rsi_overbought
      - *breakout_fail_up
    time_based:
      max_duration: "1w"
  short:
    mode: any
    conditions:
      - *rsi_oversold
      - *breakout_fail_down
    time_based:
      max_duration: "1w"

risk:
  position_sizing:
    type: percentage
    value: 1.0
  sl:
    type: trailing
    step: 0.004
    activation_price: 0.002
    cap: 0.03
  tp:
    type: multi_target
    targets:
      - value: 1.0
        percent: 60
        move_stop: true
      - value: 2.0
        percent: 40
        move_stop: false
